- eopkg:
  - albert
  - atom
  - bind-utils
  - budgie-screenshot-applet
  - calibre
  - clipit
  - discord
  - docker
  - exercism-cli
  - feedreader
  - gedit-plugins
  - ghex
  - ghostwriter
  - git
  - gitg
  - glances
  - gnome-calendar
  - gnome-clocks
  - gnome-contacts
  - gnome-dictionary
  - gnome-disk-utility
  - gnome-font-viewer
  - gnome-multi-writer
  - gnome-pomodoro
  - gnome-screenshot
  - gnome-tweak-tool
  - gnome-weather
  - go-for-it
  - golang
  - handbrake
  - htop
  - hub
  - libreoffice-writer
  - meld
  - mosh
  - mpv
  - mumble
  - n1
  - neofetch
  - nodejs
  - obs-studio
  - openjdk-8
  - p7zip
  - paper-icon-theme
  - php
  - pinta
  - pip
  - pycrypto
  - ranger
  - redshift
  - ruby
  - sqlcipher
  - sqlcipher-devel
  - sqlite3
  - sqlite3-devel
  - steam
  - telegram
  - tilda
  - tk # git-gui
  - tmux
  - tree
  - vagrant
  - vim
  - vlc
  - vscode
  - wget
  - xclip
  - zeal
  - zsh
