- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash_profile: bash_profile
    ~/Bilder/BitDay: files/BitDay
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.config/plasma-workspace/env/ssh-add.sh: config/KDE/ssh-add.sh
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc:
      force: true
      path: zshrc

- shell:
    - ['mkdir -p ~/REPOS/{lsw,private,school,github,work,projects}', 'Setting up REPO directories... ']
    - ['git submodule update --init --recursive', 'Installing submodules... ']
    - ['git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; ~/.fzf/install --all', 'Install fuzzy command-line finder (fzf)... ']
    - ['sudo -H pip install thefuck', 'Install "thefuck"... ']
    - ['fonts/install.sh', 'Install powerline fonts... ']
    - ['~/Bilder/BitDay/install_cron.sh', 'Install cron jobs for BitDay... ']
    - ['rsync -rtuvP ~/.dotfiles/configs/konsole/ ~/.local/share/konsole/', 'Sync "Konsole" configs... ']

