- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash_profile: bash_profile
    ~/Bilder/BitDay: files/BitDay
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.vim: vim
    ~/.tmux: tmux
    ~/.tmux.conf: tmux/.tmux.conf
    ~/.tmux.conf.local: tmux.conf
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc:
      force: true
      path: zshrc

- shell:
    - ['mkdir -p ~/REPOS/{lsw,private,school,github,work,projects}', 'Setting up REPO directories... ']
    - ['git submodule update --init --recursive', 'Installing submodules... ']
    - ['git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; ~/.fzf/install --all', 'Install fuzzy command-line finder (fzf)... ']
    - ['sudo -H pip install thefuck', 'Install "thefuck"... ']
    - ['fonts/install.sh', 'Install powerline fonts... ']
